language: android
android:
  components:
  - platform-tools
  - build-tools-27.0.3
  - android-27
  - extra-android-m2repository
before_install:
  - openssl aes-256-cbc -K $encrypted_5b0e5eaedfc3_key -iv $encrypted_5b0e5eaedfc3_iv
    -in google-services.json.enc -out app/google-services.json -d
  - chmod +x gradlew
install:
  - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v
before_cache:
  - rm -f  $HOME/.gradle/caches/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
- ./gradlew build

branches:
  only:
  - master
