version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Gradle clean
          command: ./gradlew clean
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Run Tests
          command: bundle exec fastlane android test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  crashlytics_beta:
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Gradle clean
          command: ./gradlew clean
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Create crashlytics beta
          command: bundle exec fastlane android beta api_token="$(CRASHLYTICS_API_TOKEN)" build_secret="$(CRASHLYTICS_BUILD_SECRET)"

workflows:
  version: 2
  pr_builder:
    jobs:
      - build
      - crashlytics_beta