version: 2

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Decrypt Fabric File
          command: openssl aes-256-cbc -d -md sha256 -in fabric-prop-encrypted -out fabric.properties -k $FABRIC_PROPERTIES_KEY
      - run:
          name: Gradle clean
          command: ./gradlew clean
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Run Tests
          command: bundle exec fastlane android test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  hockey_beta:
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Gradle clean
          command: ./gradlew clean
      - run:
          name: Bundle install
          command: bundle install
      - run:
          name: Create hockey beta
          command: bundle exec fastlane android beta api_token:$HOCKEY_API_TOKEN

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - hockey_beta:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              only: /beta.*/

